workflows:
  ios-release:
    name: iOS Release (App Store)
    instance_type: mac_mini
    max_build_duration: 30

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean & get deps
        script: |
          flutter clean
          flutter pub get

      - name: Analyze
        script: flutter analyze

      - name: Build App Store IPA
        script: |
          flutter build ipa \
            --export-method app-store \
            --build-name 1.0.0 \
            --build-number 1

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
  app_store_connect:
    api_key:        $APP_STORE_CONNECT_API_KEY
    api_key_id:     $APP_STORE_CONNECT_API_KEY_ID
    api_issuer:     $APP_STORE_CONNECT_API_ISSUER
    tests:          false
    enabled:        true
