workflows:
  ios-release:
    name: iOS Release (App Store)

    # macchina e timeout
    instance_type: mac_mini
    max_build_duration: 30

    # flutter / xcode e variabili
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.andreapizzola.thegiftlist"
      # qui importi il gruppo che contiene tutte le 3 variabili App Store Connect
      groups:
        - appstore-connect

    # i comandi in sequenza
    scripts:
      - name: Clean & get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Analyze code
        script: flutter analyze

      - name: Build App Store IPA
        script: |
          flutter build ipa \
            --export-method app-store \
            --build-name 1.0.0 \
            --build-number 1

    # artefatti prodotti
    artifacts:
      - build/ios/ipa/*.ipa

    # pubblicazione su App Store Connect
    publishing:
      app_store_connect:
        api_key:      $APP_STORE_CONNECT_API_KEY
        api_key_id:   $APP_STORE_CONNECT_API_KEY_ID
        api_issuer:   $APP_STORE_CONNECT_API_ISSUER
        tests:        false
        enabled:      true
