workflows:
  ios-release:
    name: iOS Release (App Store)

    # macchina e timeout
    instance_type: mac_mini
    max_build_duration: 30

    # ambiente Flutter/Xcode
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.andreapizzola.thegiftlist"

    # tutti i comandi
    scripts:
      - name: Clean & get deps
        script: |
          flutter clean
          flutter pub get

      - name: Build signed IPA
        script: |
          flutter build ipa --release

    # dove trovare l’output
    artifacts:
      - build/ios/ipa/*.ipa
