name: hostagift
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  go_router: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  vector_math: ^2.2.0
  vm_service: ^15.0.2

flutter:
  uses-material-design: true
